### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by siboehm** [whsieh/qwop-ai#1]
Can you please add a licence for your project?

I like what you implemented here and would really like to play around with it, but unfortunately that is not possible if you don't specify the license under which you released your code. Many thanks!

**Comment by whsieh** [comment]
Thanks for pointing that out, Simon! I added an MIT license to the repo. Feel free to close the issue if this works for you.

**Comment by siboehm** [comment]
Thank you!

**Comment by siboehm** [comment]
Thank you!
